### ISSUE TITLE
cannot find header on valid zip file

### ISSUE THREAD

**Issue by trashhalo** [ananthakumaran/zstream#14]
[demo.docx](https://github.com/ananthakumaran/zstream/files/9805638/demo.docx)

Docx files are zip files. This docx file from [docxelixir](https://github.com/andrewaguiar/docxelixir/blob/master/samples/demo.docx) does not parse with zstream but does parse with erlang's :zip and the linux unzip command.

```bash
** (Zstream.Unzip.Error) Invalid zip file, could not find any signature header
     code: result = Docxelixir.read_paragraphs('samples/demo.docx')
     stacktrace:
       (zstream 0.6.3) lib/zstream/unzip.ex:209: Zstream.Unzip.next_header/2
       (zstream 0.6.3) lib/zstream/unzip.ex:199: Zstream.Unzip.file_data/2
       (zstream 0.6.3) lib/zstream/unzip.ex:180: Zstream.Unzip.filename_extra_field/2
       (elixir 1.14.0) lib/stream.ex:989: Stream.do_transform_user/6
       (elixir 1.14.0) lib/stream.ex:942: Stream.do_transform/5
       (elixir 1.14.0) lib/enum.ex:4307: Enum.reduce/3
```

**Comment by ananthakumaran** [comment]
I have merged a fix to master, test it out and let me know, I will cut a release.

BTW, read the [notes](https://hexdocs.pm/zstream/Zstream.html#unzip/1-notes) under the unzip function documentation carefully before choosing this library. Zstream only supports files that can be unzipped in a streaming fashion, as the name implies.
